# Generated by Django 2.2.4 on 2020-03-03 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'forma',
                'verbose_name_plural': 'formas',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Tipos_de_Espuma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_espuma', models.CharField(max_length=200)),
                ('formulacion_o_clave', models.CharField(blank=True, max_length=200)),
                ('multiplicador', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('familia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('densidad_descripcion', models.CharField(blank=True, max_length=200)),
                ('densidad_objetivo_minima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('densidad_objetivo_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dureza_objetivo_minima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dureza_objetivo_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Flujo_de_aire_minimo', models.IntegerField(blank=True, null=True)),
                ('flujo_de_aire_maximo', models.IntegerField(blank=True, null=True)),
                ('retardante_flama', models.CharField(blank=True, max_length=200)),
                ('anti_bacterial', models.CharField(blank=True, max_length=200)),
                ('anti_estatica', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(blank=True, max_length=200)),
                ('elongacion', models.CharField(blank=True, max_length=200)),
                ('histasis', models.CharField(blank=True, max_length=200)),
                ('sag_factor', models.CharField(blank=True, max_length=200)),
                ('extra1', models.CharField(blank=True, max_length=200)),
                ('extra2', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'TipodeEspuma',
                'verbose_name_plural': 'Tipos_de_Espuma',
                'ordering': ('tipo_de_espuma',),
            },
        ),
        migrations.CreateModel(
            name='Tipos_de_Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_unidad', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tipo de unidad',
                'verbose_name_plural': 'Tipos de unidades',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='BloqueMedidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('largo_frio_objetivo', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ancho_frio_objetivo', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('alto_frio_objetivo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('flujo_de_aire_objetivo', models.IntegerField(blank=True, null=True)),
                ('largo_caliente_setting_predefinido', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ancho_caliente_setting_predefinido', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('alto_caliente_setting_predefinido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cliente', models.CharField(blank=True, max_length=200, null=True)),
                ('medida_dispobible', models.BooleanField(default=True)),
                ('disponible', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('stock', models.IntegerField(default=500, editable=False)),
                ('forma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espumas.Formas')),
                ('tipo_de_espuma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espumas.Tipos_de_Espuma')),
                ('tipo_de_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espumas.Tipos_de_Unidad')),
            ],
            options={
                'verbose_name': 'Bloque Medidas',
                'verbose_name_plural': 'Bloques Medidas',
                'ordering': ('tipo_de_espuma', 'tipo_de_unidad'),
            },
        ),
    ]
