# Generated by Django 2.2.4 on 2020-03-31 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espumas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloquemedidas',
            old_name='cliente',
            new_name='uso_objetivo',
        ),
    ]
