# Generated by Django 2.2.4 on 2020-04-29 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espumas', '0002_auto_20200331_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloquemedidas',
            name='flujo_de_aire_objetivo',
        ),
        migrations.RemoveField(
            model_name='tipos_de_espuma',
            name='Flujo_de_aire_minimo',
        ),
        migrations.RemoveField(
            model_name='tipos_de_espuma',
            name='flujo_de_aire_maximo',
        ),
    ]
