# Generated by Django 2.2.4 on 2020-04-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espumas', '0006_remove_bloquemedidas_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloquemedidas',
            name='alto_caliente_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bloquemedidas',
            name='alto_caliente_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bloquemedidas',
            name='alto_caliente_parametro_alto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bloquemedidas',
            name='alto_caliente_parametro_bajo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bloquemedidas',
            name='ancho_caliente_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bloquemedidas',
            name='ancho_caliente_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bloquemedidas',
            name='ancho_caliente_parametro_alto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bloquemedidas',
            name='ancho_caliente_parametro_bajo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bloquemedidas',
            name='largo_caliente_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bloquemedidas',
            name='largo_caliente_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bloquemedidas',
            name='largo_caliente_parametro_alto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bloquemedidas',
            name='largo_caliente_parametro_bajo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
