# Generated by Django 2.2.4 on 2020-05-13 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espumas', '0007_auto_20200430_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipos_de_espuma',
            old_name='densidad_tipo',
            new_name='densidad_objetivo',
        ),
        migrations.RenameField(
            model_name='tipos_de_espuma',
            old_name='dureza_tipo',
            new_name='dureza_objetivo',
        ),
    ]
