# Generated by Django 2.2.12 on 2020-07-02 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espumas', '0009_auto_20200513_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloquemedidas',
            name='medida_dispobible',
        ),
    ]
