# Generated by Django 2.2.12 on 2020-07-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espumas', '0011_bloquemedidas_familia_de_medidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloquemedidas',
            name='familia_de_medidas',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
