# Generated by Django 2.2.12 on 2020-07-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espumas', '0012_auto_20200702_0159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloquemedidas',
            options={'ordering': ('familia_de_medidas', 'tipo_de_espuma', 'tipo_de_unidad'), 'verbose_name': 'Bloque Medidas', 'verbose_name_plural': 'Bloques Medidas'},
        ),
    ]
