# Generated by Django 4.1.7 on 2023-09-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espumas', '0013_auto_20200702_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloquemedidas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='formas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tipos_de_espuma',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tipos_de_unidad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
