# Generated by Django 2.2.4 on 2020-03-03 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espumas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('pre_orden', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Corrida',
            },
        ),
        migrations.CreateModel(
            name='ElementoCorrida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('bloqueMedidas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espumas.BloqueMedidas')),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corrida.Corrida')),
            ],
            options={
                'db_table': 'ElementoCorrida',
            },
        ),
    ]
