# Generated by Django 2.2.4 on 2020-03-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrida',
            name='cencelada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corrida',
            name='pendiente_prod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corrida',
            name='producto_terminado',
            field=models.BooleanField(default=False),
        ),
    ]
