# Generated by Django 2.2.4 on 2020-03-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0002_auto_20200304_0358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corrida',
            old_name='cencelada',
            new_name='cancelada',
        ),
        migrations.RenameField(
            model_name='corrida',
            old_name='pendiente_prod',
            new_name='en_produccion',
        ),
        migrations.AddField(
            model_name='corrida',
            name='pendiente_produccion',
            field=models.BooleanField(default=False),
        ),
    ]
