# Generated by Django 2.2.4 on 2020-03-04 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0004_auto_20200304_0442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corrida',
            old_name='pre_ordenn',
            new_name='pre_orden',
        ),
    ]
