# Generated by Django 2.2.4 on 2020-03-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0006_auto_20200304_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrida',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
