# Generated by Django 2.2.4 on 2020-03-25 04:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0007_corrida_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corrida',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='corrida',
            name='fecha_programada',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='elementocorrida',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elementocorrida',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='BloqueProducido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('alto_caliente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('peso_caliente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('flujo_de_aire_caliente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('elemento_corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corrida.ElementoCorrida')),
            ],
            options={
                'db_table': 'BloqueProducido',
            },
        ),
    ]
