# Generated by Django 2.2.4 on 2020-03-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0009_auto_20200325_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloqueproducido',
            name='alto_caliente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloqueproducido',
            name='flujo_de_aire_caliente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloqueproducido',
            name='peso_caliente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
