# Generated by Django 2.2.4 on 2020-04-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0010_auto_20200325_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueproducido',
            name='ancho_caliente',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloqueproducido',
            name='comentario',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='bloqueproducido',
            name='largo_caliente',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
