# Generated by Django 2.2.4 on 2020-04-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0011_auto_20200404_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloqueproducido',
            name='defecto',
            field=models.CharField(choices=[('sd', ''), ('ph', 'Pinhole'), ('g', 'Grieta'), ('v', 'Vena'), ('mm', 'Mal manejo'), ('fdm', 'Fuera de medida'), ('a', 'Algodonozo')], default='sd', max_length=2),
        ),
    ]
