# Generated by Django 2.2.4 on 2020-04-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0012_auto_20200415_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementocorrida',
            name='turno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
