# Generated by Django 2.2.4 on 2020-04-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0013_elementocorrida_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueproducido',
            name='lote',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
