# Generated by Django 2.2.4 on 2020-04-23 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0014_bloqueproducido_lote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementocorrida',
            name='turno',
        ),
    ]
