# Generated by Django 2.2.12 on 2020-04-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0015_remove_elementocorrida_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueproducido',
            name='densidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bloqueproducido',
            name='volumen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
