# Generated by Django 2.2.4 on 2020-04-29 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0016_auto_20200423_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloqueproducido',
            name='lote',
        ),
    ]
