# Generated by Django 2.2.4 on 2020-04-29 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0018_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementocorrida',
            name='lote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='corrida.Lote'),
            preserve_default=False,
        ),
    ]
