# Generated by Django 2.2.4 on 2020-05-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0022_auto_20200430_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='densidad_capturada',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='dureza_capturada',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='flujo_de_aire_astm_capturado',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='sag_factor_capturado',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
