# Generated by Django 2.2.12 on 2020-05-08 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0023_auto_20200507_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementocorrida',
            name='lote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corrida.Lote'),
        ),
    ]
