# Generated by Django 2.2.12 on 2020-07-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0026_auto_20200702_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloqueproducido',
            name='defecto',
            field=models.CharField(choices=[('sd', ''), ('ph', 'Pinhole'), ('g', 'Grieta'), ('v', 'Vena'), ('mm', 'Mal manejo'), ('fm', 'Fuera de medida'), ('a', 'Algodonozo'), ('ma', 'Manchado')], default='sd', max_length=2),
        ),
    ]
