# Generated by Django 2.2.12 on 2020-07-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0027_auto_20200702_0620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elementocorrida',
            options={'ordering': ['lote']},
        ),
        migrations.AddField(
            model_name='corrida',
            name='fecha_creacion',
            field=models.DateTimeField(null=True),
        ),
    ]
