# Generated by Django 4.1.7 on 2023-09-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0030_bloqueproducido_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloqueproducido',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='corrida',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='elementocorrida',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
