# Generated by Django 4.2.5 on 2023-10-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0031_alter_bloqueproducido_id_alter_corrida_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrida',
            name='cedis',
            field=models.CharField(choices=[('Monterrey', 'Monterrey'), ('Salinas', 'Salinas')], default='Monterrey', max_length=122),
        ),
    ]
